language: node_js
node_js:
- "10.24.1"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run GoogleApiBooks.postman_collection.json -d id.csv